### ISSUE TITLE
3cpio does not mention helper programs

### ISSUE THREAD

**Issue by tpowa** [bdrung/3cpio#4]
**3cpio fails with:**
`3cpio: Error: Failed to extract content of ../tmp/bla.img: No such file or directory (os error 2)`
if the helper like zstd, xz etc. is not found in PATH.

**Comment by bdrung** [comment]
Can you review the proposed improvement in https://github.com/bdrung/3cpio/pull/7? Is that change error message good or can you suggest a better wording?
