### ISSUE TITLE
3cpio overwrites xattrs like suid/gid

### ISSUE THREAD

**Issue by tpowa** [bdrung/3cpio#5]
Extracting files overwrites  xattrs like suid/guid bit. Code parts which are affected are reffered below.

**Comment by bdrung** [comment]
Can you provide a small example? E.g. a small cpio file?

**Comment by tpowa** [comment]
[test.cpio.zstd.gz](https://github.com/user-attachments/files/16283854/test.cpio.zstd.gz)
typicall /usr/bin/umount is setuid root

**Comment by tpowa** [comment]
Ah and I run 3cpio as root on this file, so permissions should be preserved.

**Comment by tpowa** [comment]
As addition setguid is also ignored so the cpio field of the extended attributes needs to be implemented.
chmod +g file to set this attribute on a file.

**Comment by tpowa** [comment]
Ok found a way to get it working, you need to remove the part with preserve the permissions:
Remove this from line 396:
---
    if preserve_permissions {
        chown(&header.filename, Some(header.uid), Some(header.gid))?;
    }
---
Remove this from line 484:
---
    if preserve_permissions {
        fchown(&file, Some(header.uid), Some(header.gid))?;
    }
---
If I understand the code correct you need to negate or remove this check.
Change to 396 and 484:
---
    if ! preserve_permissions {
---
Then all is fine :)
